baseURL = 'https://slowmadders.com/'
languageCode = 'en-gb'
title = 'Vanlife Travel Blog — Slowmadders'
copyright = 'This website was designed and built by Charlie using Hugo and Cloudflare Pages. © 2024'



[[menus.main]]
name = 'Vanlife Travel Blog'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Our story'
pageRef = '/about'
weight = 20

[[menus.main]]
url = 'https://www.instagram.com/slowmadders/'
name = 'Instagram'
weight = 30



[[menus.main-signoff]]
url = 'mailto:hello@slowmadders.com'
name = 'hello@slowmadders.com'
weight = 10

[[menus.main-signoff]]
url = 'https://www.instagram.com/slowmadders/'
name = 'Instagram'
weight = 30



[module]
[module.hugoVersion]
extended = false
min = "0.116.0"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true