baseURL = '/'
languageCode = 'en-gb'
title = 'Vanlife Travel Blog — Slowmadders'
copyright = 'This website was designed and built by Charlie using Hugo and Cloudflare Pages. © 2024'
aboutImage = '/homepage-bubble.jpg'


[[menus.header]]
name = 'Vanlife Travel Blog'
pageRef = '/'
weight = 10

[[menus.header]]
name = 'Our story'
pageRef = '/about'
weight = 20

[[menus.header]]
url = 'mailto:hello@slowmadders.com'
name = 'hello@slowmadders.com'
weight = 30



[[menus.footer]]
name = 'Vanlife Travel Blog'
pageRef = '/'
weight = 10

[[menus.footer]]
name = 'Our story'
pageRef = '/about'
weight = 20

[[menus.footer]]
name = 'RSS feed'
url = '/index.xml'
weight = 30



[[menus.footer-signoff]]
url = 'mailto:hello@slowmadders.com'
name = 'hello@slowmadders.com'
weight = 10

[[menus.footer-signoff]]
url = 'https://www.instagram.com/slowmadders/'
name = 'Instagram'
weight = 20



[[menus.instagram]]
url = 'https://www.instagram.com/slowmadders/'
name = 'Instagram'
weight = 10



[module]
[module.hugoVersion]
extended = false
min = "0.116.0"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true