baseURL = 'https://slowmadders.com/'
languageCode = 'en-gb'
title = 'Vanlife Travel Blog — Slowmadders'


[[menus.main]]
name = 'Vanlife Travel Blog'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Our story'
pageRef = '/about'
weight = 20


[[menus.main-instagram]]
url = 'https://www.instagram.com/slowmadders/'
name = 'Instagram'
weight = 30


[[menus.main-signoff]]
url = 'mailto:hello@slowmadders.com'
name = 'hello@slowmadders.com'
weight = 10


[module]
[module.hugoVersion]
extended = false
min = "0.116.0"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true